import Head from 'next/head';

const LAST_UPDATED = 'September 17, 2026';

export default function Privacy() {
  return (
    <>
      <Head><title>Privacy Policy - OnlyOne</title></Head>
      <div className="min-h-screen bg-gradient-luxury text-white px-6 py-16">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-black premium-title mb-2">Privacy Policy</h1>
          <p className="text-gray-500 text-sm mb-10">Last updated: {LAST_UPDATED}</p>

          <div className="premium-card p-8 space-y-8 text-sm text-gray-300 leading-relaxed">
            <Section title="1. What We Collect">
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  <strong>Account info.</strong> A password, and either an email address or a username you
                  choose — see Section 2, Fan Anonymity.
                </li>
                <li>
                  <strong>Creator profile info.</strong> What a creator puts on their own profile —
                  display name, handle, bio, tags, avatar, and a payout wallet address. We do not
                  currently collect government-issued ID or a selfie from creators. If we add formal
                  identity verification, this policy will say so before that collection starts.
                </li>
                <li>
                  <strong>Fan age-verification info.</strong> Some states now require real age verification
                  (not just a checkbox) before an adult site can let a visitor in. Where that applies, we
                  use a third-party age-verification vendor to confirm you're of legal age — see Section 6.
                  That vendor handles whatever information their verification method requires (e.g., a
                  government-issued ID or a database match) under their own privacy terms; we retain only
                  what's needed to know your visit was verified.
                </li>
                <li>
                  <strong>Content.</strong> Anything you upload — creator posts and media, marketplace
                  listings, messages, wall comments.
                </li>
                <li>
                  <strong>Wallet addresses and on-chain activity.</strong> If you connect a wallet or make a
                  payment, we see that wallet's address and the transactions it sends to or receives from
                  the Platform. See Section 4 — this data is not private in the way the rest of this policy
                  describes.
                </li>
                <li>
                  <strong>Basic usage data.</strong> Standard technical logs (IP address, browser/device
                  info, timestamps) generated by using any website, kept for security and abuse prevention.
                </li>
                <li>
                  <strong>Launch notification signup.</strong> If you ask to be notified when we launch,
                  we store the email address you give us, whether you said you were joining as a fan or
                  a creator, which page you signed up from, and (if we can tell) the US state you were
                  in — the last one only so we can tell you when your state opens, since some states are
                  currently blocked entirely. That list is used for nothing but telling you about the
                  launch. We never sell or share it, and you can be removed at any time by emailing{' '}
                  <a href="mailto:team@onlyone1.fun" className="text-brand-gold underline">team@onlyone1.fun</a>.
                  You do not need an account to sign up, and signing up does not create one.
                </li>
                <li>
                  <strong>Content-report info.</strong> If you submit our{' '}
                  <a href="/report-content" className="text-brand-gold underline">Report Non-Consensual Content</a>{' '}
                  form (no account needed to do so), we collect the name and contact info you provide and
                  what you tell us about the content, solely to review and act on that report.
                </li>
              </ul>
            </Section>

            <Section title="2. Fan Anonymity — What We Deliberately Don't Require">
              <p>
                A Fan account never requires a real email address. You can sign up with a username instead
                — we understand plenty of people using this Platform would rather it never show up in an
                inbox someone else can see. If you do use a real email, we still never send marketing to it
                without your consent, and we never use it for anything other than identifying your own
                account.
              </p>
              <p className="mt-3">
                This is a deliberate design choice, not an oversight: the less real-world identifying
                information a Fan account requires, the less there is to ever be exposed, subpoenaed
                unnecessarily, or leaked. Creator accounts are held to a different standard (Section 1) —
                that verification exists to keep minors and non-consenting people off the Platform, which
                we treat as non-negotiable regardless of the privacy tradeoff.
              </p>
            </Section>

            <Section title="3. How We Use It">
              <ul className="list-disc pl-5 space-y-2">
                <li>To operate your account, log you in, and show you the content you've paid to unlock.</li>
                <li>To review a creator's profile before it goes public.</li>
                <li>To process payments and calculate fees.</li>
                <li>To detect and prevent fraud, abuse, and violations of our Terms of Service.</li>
                <li>To respond to a valid legal request (subpoena, court order) where we're required to.</li>
              </ul>
              <p className="mt-3">We do not sell your personal information to third parties, and we do not use your content or account data to train AI models.</p>
            </Section>

            <Section title="4. Blockchain & On-Chain Data Is Public">
              <p>
                Payments on this Platform happen as direct, on-chain cryptocurrency transactions (see the{' '}
                <a href="/terms#marketplace" className="text-brand-gold underline">Terms of Service</a>).
                Blockchains are public ledgers by design: a wallet address and every transaction it sends or
                receives is visible to anyone who looks, forever, on the blockchain itself — not just to us.
                We cannot make on-chain data private, and we cannot delete, alter, or reverse anything once
                it's confirmed on-chain, even if you later delete your Platform account. If linking a wallet
                to your real identity is a concern, don't fund it from an address or exchange account that's
                already tied to your name.
              </p>
            </Section>

            <Section title="5. Cookies & Sessions" id="cookies">
              <p>
                We use a single session cookie to keep you logged in. We don't currently run third-party
                advertising trackers or analytics cookies on the Platform.
              </p>
            </Section>

            <Section title="6. Third-Party Services">
              <p>
                We use infrastructure providers (hosting, file storage, and an age-verification vendor,
                AgeChecker.Net, for fans in states that require it) to run the Platform. Those providers
                can access the specific data needed to perform their function (e.g., storage providers
                hold uploaded files; AgeChecker.Net handles age-verification documents) under their own
                confidentiality and security obligations — we don't hand any of them more than what's
                needed for that purpose.
              </p>
            </Section>

            <Section title="7. Data Retention & Deletion">
              <p>
                You can request deletion of your account and associated off-chain data (profile info,
                messages, uploaded content) at any time by contacting support. Some limits on that:
              </p>
              <ul className="list-disc pl-5 space-y-2 mt-3">
                <li>On-chain transaction history cannot be deleted — see Section 4.</li>
                <li>
                  Creator identity-verification records may be retained beyond account deletion where we're
                  legally required to keep them (e.g., recordkeeping rules for adult-content platforms).
                </li>
                <li>We may retain limited data where necessary to investigate fraud, abuse, or a legal claim already in progress.</li>
              </ul>
            </Section>

            <Section title="8. Your Rights">
              <p>
                Depending on where you live, you may have rights to access, correct, or request deletion of
                your personal information, or to object to certain uses of it. Contact support to exercise
                any of these — we'll respond consistent with applicable law, subject to the retention limits
                in Section 7.
              </p>
            </Section>

            <Section title="9. Children's Privacy">
              <p>
                This Platform is strictly for adults 18 and older (see the Terms of Service, Section 1). We
                do not knowingly collect information from anyone under 18. If we learn an account belongs to
                a minor, it will be terminated immediately and any associated data handled as required by
                law.
              </p>
            </Section>

            <Section title="10. Changes to This Policy">
              <p>
                We may update this Privacy Policy from time to time. Continued use of the Platform after a
                change is posted constitutes acceptance of the revised policy. Material changes will be
                reflected by an updated "Last updated" date above.
              </p>
            </Section>

            <Section title="11. Contact">
              <p>Questions about this policy, or a data request under Section 7 or 8, can be directed to the Platform's support contact.</p>
            </Section>
          </div>

          <p className="text-xs text-gray-600 mt-8">
            This document is a general template and does not constitute legal advice. It should be
            reviewed by a licensed attorney familiar with adult content platforms, cryptocurrency
            regulations, and data privacy law (e.g. GDPR/CCPA) in your operating jurisdiction before public
            launch.
          </p>
        </div>
      </div>
    </>
  );
}

function Section({ title, id, children }) {
  return (
    <section id={id}>
      <h2 className="text-lg font-bold text-brand-gold mb-2">{title}</h2>
      {children}
    </section>
  );
}
